### ISSUE TITLE
Provide a language switch

### ISSUE THREAD

**Issue by leofeyer** [contao/check#1]
There is a routine to switch the language already, which can be triggered with a URL parameter:
- `?lng=en`
- `?lng=de_DE`

However, there is no clickable language menu yet.

**Comment by michelbalzer** [comment]
Also the language option is not added to the links, so if I want to go to from */check/?lng=de_DE* to *check/?c=live-update*, it's wieder in english.

**Comment by fritzmg** [comment]
@leofeyer do we still want that? 😁

**Comment by leofeyer** [comment]
I don't think so. 😄
