### ISSUE TITLE
Error 500: Cannot redeclare posix_getpwuid()

### ISSUE THREAD

**Issue by barrystaes** [contao/check#100]
When doublechecking everything because i had problems setting up Contao 3.5.15 i descided to go by-the-book and even use the Check tool first.

But it gave an error 500.. The log shows this error message:

    PHP Fatal error:  Cannot redeclare posix_getpwuid() in /home/myuser/domains/mydomain.com/public_html/check/controller/bootstrap.php on line 172

Thats [this code](https://github.com/contao/check/blob/8f8a2ebc0fd9e2d5b2a908dfdb427b9fa0d125c9/check/controller/bootstrap.php#L172).

I used the latest version `contao-check-10.20-0-g8f8a2eb.zip`, on a fairly new CentOS7 server with Apache 2.4.23, Php 5.6.25, and MariaDB 5.5.51.

**Comment by leofeyer** [comment]
See #93.

**Comment by fritzmg** [comment]
@leofeyer there is no solution for the problem in #93

**Comment by leofeyer** [comment]
Yes there is a solution: https://github.com/contao/check/issues/93#issuecomment-222139566

**Comment by fritzmg** [comment]
That's a more specific case, when `posix_getpwuid` has been disabled - not sure if that covers all instances of this problem. @barrystaes is that true in your case?

**Comment by barrystaes** [comment]
Thanks @leofeyer and @fritzmg your responses helped.

In my case its caused by this in `php.ini`:

```
; This directive allows you to disable certain functions for security reasons.
; It receives a comma-delimited list of function names.
; http://php.net/disable-functions
disable_functions = exec,system,passthru,shell_exec,escapeshellarg,escapeshellcmd,proc_close,proc_open,dl,popen,show_source,posix_kill,posix_mkfifo,posix_getpwuid,posix_setpgid,posix_setsid,posix_setuid,posix_setgid,posix_seteuid,posix_setegid,posix_uname
```

Which was added to my PHP configuration by DirectAdmin with CustomBuild 2.0 using the "Secure PHP" option.

I'm hesatant to remove `posix_getpwuid` from this list however.. security wise.
