### ISSUE TITLE
add Content-Type header for charset

### ISSUE THREAD

**Issue by fritzmg** [contao/check#104]
Some wild hosters might have a default charset other than `utf-8` configured. This will lead to garbled text in the contao check since the `Content-Type` header takes precedence over the `<meta charset="utf-8">` definition in the output (http://stackoverflow.com/a/7103606/374996).

May be

``` php
header('Content-Type: text/html; charset=utf-8');
```

can be simply added to `Router::dispatch`.

**Comment by leofeyer** [comment]
Closing this in favour of #104.
