### ISSUE TITLE
minimum PHP version

### ISSUE THREAD

**Issue by fritzmg** [contao/check#110]
Currently, the minimum PHP version for the Contao Check seems to be `5.3.0`, due to the `static::` references » http://php.net/manual/it/language.oop5.late-static-bindings.php

In PHP `5.2.17` or lower, you'll get
```
Parse error: syntax error, unexpected T_STATIC in …/index.php on line 34
```
See https://3v4l.org/FCFcP for example.

Since the Contao Check should provide information about whether or not the server environment is suitable for a Contao installation, shouldn't the minimum PHP compatibility be at least `5.2.0` for example?

**Comment by leofeyer** [comment]
IMHO, the minimum PHP version should be one of the maintained versions, so PHP 5.5 or PHP 5.6.

**Comment by fritzmg** [comment]
👍
