### ISSUE TITLE
Check 12.0 bietet nur Contao 3.5.18 zur Installation an

### ISSUE THREAD

**Issue by 31er** [contao/check#111]
Der Systemcheck 12.0.0 hat nur Contao 3.5.18 (LTS) als Auswahl zur Installation. Sollte nicht besser 3.5.19 (LTS) angeboten werden?

**Comment by fritzmg** [comment]
@leofeyer die `CURRENT_LTS_VERSION` ist ja derzeit hardcoded: https://github.com/contao/check/blob/12.0/check/includes/bootstrap.php#L31
Könnte man das nicht auch dynamisch von contao.org holen?

**Comment by leofeyer** [comment]
Ja, theoretisch schon. Allerdings müssten wir da irgendeine Art von Cache einbauen, damit das nicht in einem DDoS endet. 😄

**Comment by fritzmg** [comment]
Beim validieren wird das `.json` File ja auch vom Server geholt, sobald man auf den Button klickt. Wäre ja dann beim installieren nicht anders, oder? ;)

**Comment by leofeyer** [comment]
Jein, denn die JSON-Datei wird nur heruntergeladen, wenn sie noch nicht existiert. Das geht aber bei der Versionsnummer nicht, denn die ändert sich ja ab und an.

**Comment by fritzmg** [comment]
Ja, aber in der Regel (zumindest vermute ich das so) wird der Contao Check ja immer nur "einmalig" eingesetzt, daher gehe ich davon aus, dass auch meistens die `.json` Datei runtergeladen werden muss. Aber verstehe natürlich was du meinst.

**Comment by mlwebworker** [comment]
Ich möchte hier auch noch einmal einhaken.
Auf schwachen Paketen ohne ssh-Zugang nutze ich gern den Check zur Installation. Inzwischen ist das aber schon nicht mehr so nett, wenn ich von 3.5.18 dann erst mal noch updaten muss. Ich würde es sehr schade finden, wenn wir diese einfache Art der Installation nicht mehr nutzen können.

**Comment by mlwebworker** [comment]
Wer liest ist klar im Vorteil. Kann man ja ändern. Immer diese Frontendler!!!
Trotzdem für den "Laien" ist das nicht mehr so bequem.

**Comment by fritzmg** [comment]
@leofeyer da der Contao Check seit Version 12 nun nicht mehr mit jeder neuen Contao Version aktualisiert werden muss finde ich, dass es schon wichtig wäre, dass auch die Versionsabfrage für die Installation von Contao über den Check dynamisch ist anstatt hard gecodet. Gibt es auf contao.org bereits eine Möglichkeit bzw. ein Interface, um die aktuelle 3.5er Version abfragen zu können?

**Comment by leofeyer** [comment]
Ja: https://update.contao.org/service/lts-version.txt

**Comment by mlwebworker** [comment]
Danke finde ich Klasse Eure Arbeit

**Comment by fritzmg** [comment]
implemented in #118
