### ISSUE TITLE
"Quick-Install" per"contao-checkloader"

### ISSUE THREAD

**Issue by zonky2** [contao/check#115]
@fritzmg der "Quick-Install" per https://github.com/e-spin/contao-checkloader erfreut sich in einem (kleinen) Kreis von Usern großer Beliebtheit... da Du nun das Steuer übernommen hast, kann das gern in eine neue Version mit einfließen bzw. übernommen werden...

**Comment by leofeyer** [comment]
Es wäre auch kein Problem, den ganzen Check in eine Phar-Datei zu packen, aber das würde – genau wie der Check-Loader – gewisse Systemvoraussetzungen bedingen. Deswegen haben wir den Check bewusst so geschrieben, dass er auch ohne diese Systemvoraussetzungen läuft und dem Anwender eine hübsche Erklärung und nicht nur eine `die('Fehlermeldung')` anzeigt. Genau das wäre aber beim Check-Loader wieder der Fall.

**Comment by zonky2** [comment]
den "Quick-Loader" würde ich als Option sehen - der bisherige Weg mit "Download > Extrahieren > FTP-Upload" sollte natürlich weiterhin funktionieren...

die zwei `die()` von Zip und Curl könnte man auch abfangen und eine Meldung like "nimm den Standardweg, da der Quick-Loader bei dir nicht funktioniert"

**Comment by fritzmg** [comment]
> @fritzmg der "Quick-Install" per https://github.com/e-spin/contao-checkloader erfreut sich in einem (kleinen) Kreis von Usern großer Beliebtheit... da Du nun das Steuer übernommen hast, kann das gern in eine neue Version mit einfließen bzw. übernommen werden...

Wie soll das gemacht werden? Der contao-checkloader lädt einfach den Contao Check herunter. Wenn wir das in den Check integrieren, muss man ja ohnehin den Contao Check runterladen, um den Contao Check herunter zu laden? 😉

**Comment by zonky2** [comment]
den "Quick-Loader" kann man natürlich nicht IN das Zip einbringen, sondern AUSSERHALB als eigenständige PHP-Datei - an dem Loader ändert sich sicher nicht so oft etwas, so dass es reicht den 1x auf der Platte zum Upload zu haben - der Loader aktualisiert den Check auch, was der ja von sich aus nicht kann

**Comment by fritzmg** [comment]
Closing as this issue is outdated.
