### ISSUE TITLE
Check successful, MySQL-Backup while Live-Update not fulfilled

### ISSUE THREAD

**Issue by ngdot** [contao/check#119]
Hi, my contao-check says that i'm able to use the live-updater but if I use it the backup 
conditions are not fulfilled. Any Ideas? Does the contao-check check the backup requirements? I think it should!

**Comment by fritzmg** [comment]
@leofeyer what are the requirements for creating a backup in the Contao Check? I guess these requirements should also be checked in the Contao Check in the Live-Update section?

**Comment by leofeyer** [comment]
DB backups are optional in the Live Update client and will be made if the `mysqldump` and `mysql` binaries are available for PHP.
