### ISSUE TITLE
wrong colors for composer requirements 

### ISSUE THREAD

**Issue by NicolasGoerlach** [contao/check#123]
![screenshot-no-events de-2017-05-17-12-14-51](https://cloud.githubusercontent.com/assets/8327905/26149443/a226daa2-3afa-11e7-8bcb-70131e934f29.png)

**Comment by BugBuster1701** [comment]
Das is OK so, denn es ist kein Fehler in dem Fall sondern eine Bedingung.

**Comment by leofeyer** [comment]
Korrekt.

**Comment by NicolasGoerlach** [comment]
Ah okay – sorry, bisschen verwirrend.
