### ISSUE TITLE
[Apache] Include 'AllowOverride' check

### ISSUE THREAD

**Issue by ADoebeling** [contao/check#129]
If you try to install contao4 on a default-apache with 'AllowOverride none` (and without permission to edit the vHost.conf) the `.htaccess` and the defined page alias aren't working

**Comment by fritzmg** [comment]
I am not sure if this is something we can and should check. In order to retrieve configuration options from Apache, `mod_info` needs to be enabled (see [here](https://stackoverflow.com/questions/6759758/get-apache-configuration-from-php-script) for example).

**Comment by ADoebeling** [comment]
Maybe we could check this by try and error?

`apache-check/.htaccess` => RewriteRule that loads a specific .txt-file

check if `/apache-check/` returns the content of the txt-file?

**Comment by fritzmg** [comment]
This could at most only be a warning, since it's up to the user which web server to use and how to configure it.

**Comment by ADoebeling** [comment]
> This could at most only be a warning, since it's up to the user which web server to use 

It makes sense to perform the `/apache-check/` only if the detected webserver is an apache. ;-)

> and how to configure it.

I'd expect that apache-configurations that don't allow you to use a .htaccess with rewrite-rules are a problem for the most users.

**Comment by fritzmg** [comment]
This should be integrated into the Contao Manager, if at all.
