### ISSUE TITLE
[php.ini] Short tags

### ISSUE THREAD

**Issue by ADoebeling** [contao/check#130]
I've recently got in trouble because a theme used php short tags that wasn't supported by the customer server.

AFAIK this is not a contao4-requirement, but a Notice would be great.

**Comment by fritzmg** [comment]
Do you mean `<? ... ?>`? What issues did you have with that? Having short tags enabled or disabled is not a basic requirement for Contao 3 or 4.

**Comment by ADoebeling** [comment]
> Do you mean <? ... ?>?

yes / ok

**Comment by fritzmg** [comment]
The Contao Check does Check the requirements of Themes, just of Contao. It needs to be documented by the Theme and not the Contao Check.

There are lots of other things that themes or extensions could require, that the Contao Check does not check for. It would make no sense to check or document those things in the Contao Check.

**Comment by Aybee** [comment]
Maybe he talks about.
```php
<?= $this->foo ?>
```
I once also was on a server where this did not work. But it was a 2.11 installation, where I was coding a template with this short echo tag. I was wondering why this did not work and continued with
```php
<?php echo $this->foo ?>
```
So I did not figure out the reason.

**Comment by ADoebeling** [comment]
@Aybee 

> since php 5.4.0 | The tag <?= is always available regardless of the short_open_tag ini setting.

So this should work anyway

**Comment by Aybee** [comment]
Ah, ok. I also remembered the customer and I checked the version which realy is PHP 5.3.29 😳
