### ISSUE TITLE
Check for PHP-FPM

### ISSUE THREAD

**Issue by fritzmg** [contao/check#134]
As discussed with @Toflar the recommended PHP SAPI for Contao 4 is PHP-FPM, since only within this environment the `kernel.terminate` events can be processed without affecting the response of the main request. (Did I understand and describe that correctly?)

Otherwise it is recommended for users to disable the front end cron because if any cron tasks takes a long time, it will block the whole request.

**Comment by Toflar** [comment]
> (Did I understand and describe that correctly?)

Yes. PHP provides a function (`fastcgi_finish_request()`) that allows to send the response to the client and continue script execution for heavier tasks. However, only the php-fpm server api (SAPI) supports that (as of today).

**Comment by leofeyer** [comment]
I believe that the FastCGI implementation supports flushing the response, too. But I am generally against recommending a PHP SAPI as long as Symfony does not do it, either.

**Comment by Toflar** [comment]
No, php-fpm is the only one supporting it. I read the php source code just a few minutes ago :)

**Comment by fritzmg** [comment]
@leofeyer the problem is that now in Contao 4 the webserver will not send the page to the client, until all cron tasks are finished for example (if the webserver does not use php-fpm). Even the core tasks might take a long time (e.g. feed generation) and does every so often, the website will be unresponsive for a visitor. Thus it should be recommended to either use php-fpm or to disable the front end cron in the system settings and configure a cronjob that accesses `example.org/_contao/cron` instead, so that visitors are not affected by cron tasks.

**Comment by Toflar** [comment]
@fritzmg I agree the cron task is probably the one that's blocking the most. There are others like adding the page to the search index but they should be lighter. Generally speaking I think php-fpm is the best solution and should be recommended anyway but as there are many fast-cgi setups out there maybe it would be a good idea to have it configurable. Or maybe we should switch back to the ajax solution for the poor man's cron only (not for the other `kernel.terminate` listeners). /cc @contao/developers

**Comment by fritzmg** [comment]
Yeah, with the AJAX solution at least the _first_ request is unaffected and only a subsequent request by the visitor might be blocked, since the cron request might still be running under his session.

Btw. couldn't the latter be solved by doing
```php
session_write_close();
```
at the beginning of the cron execution? Or is that dangerous/inadvisable...

**Comment by leofeyer** [comment]
It's just a drawback of the SAPI. Nothing that we should care about – aside from explaining in the docs why PHP-FPM is the best choice. Most users have to deal with whatever the hosting company provides and have no way of changing the SAPI.

**Comment by fritzmg** [comment]
Yeah, but it's a change from Contao 3 to Contao 4 that many users will probably not know about. I didn't realise it either - until I wondered why most of our Contao 4 installations sometimes had such a long loading time.

I found out that I had heavy cron tasks in each of those installations and that the cron tasks were blocking the response. In Contao 3 this would not happen.

**Comment by leofeyer** [comment]
That's why you should use a real cron to trigger the cron script.

**Comment by fritzmg** [comment]
Yes of course.

But that's not the point of this question/suggestion. The point is that there is a difference in behavior between Contao 3 and 4 regarding the execution of TL_CRON which is completely undocumented. Developers might not know why their page sometimes takes a long time to load or they might not even realise at all that it's doing that, since it's an obscure issue.

**Comment by leofeyer** [comment]
> Developers might not know why their page sometimes takes a long time to load

And as a countermeasure we are adding a SAPI check to the Contao check? This seems odd to me. We should rather show a warning in the back end or something similar.

**Comment by aschempp** [comment]
What would a SAPI check help us? We can't *not* execute the jobs anyway?

**Comment by aschempp** [comment]
Also, a backend message would be 99% annoying and not helping anyone, because they can't change that on their hosting platform. If we want to do anything at all, it *could* be a message in the manager installation process.

**Comment by fritzmg** [comment]
> We can't not execute the jobs anyway?

The user can then disable the frontend cron and instead configure a webcron for `example.org/_contao/cron`.

**Comment by aschempp** [comment]
> The user can then disable the frontend cron and instead configure a webcron for example.org/_contao/cron.

Which is already possible (**and recommended**), regardless of a SAPI check?

**Comment by fritzmg** [comment]
> Which is already possible (and recommended), regardless of a SAPI check?

Yes, it was always recommended. But as already mentioned, there is a difference in behavior regarding the command scheduler between Contao 3 and 4. In Contao 3, the execution of the command scheduler via the frontend AJAX call will not block the (first) request of a visitor - while in Contao 4 it will (unless the webserver is running php-fpm).

**Comment by fritzmg** [comment]
Closing this. I think any such Contao 4 related checks should only be integrated in the Contao Manager.
