### ISSUE TITLE
Add ICU requirement for Contao 4.5

### ISSUE THREAD

**Issue by ausi** [contao/check#136]
Contao 4.5 needs the intl extension with the ICU version 4.6 or higher.
See https://github.com/contao/core-bundle/issues/1352#issuecomment-363116503

**Comment by fritzmg** [comment]
@ausi do you know a simple way to get the ICU version via PHP? (So that I don't have to Google 😉)

**Comment by ausi** [comment]
This should work: https://github.com/symfony/requirements-checker/blob/931997643fb512026241c7360c613bc1e61ed9cf/src/SymfonyRequirements.php#L283-L301

**Comment by fritzmg** [comment]
On my system I get a version number of `57.1`. Is that plausible?

**Comment by ausi** [comment]
Yes, that’s plausible. ICU changed the version numbering after 4.8.
They released: …, 4.2, 4.4, 4.6, 4.8, 49, 50, 51,…

**Comment by fritzmg** [comment]
weird ;). Ok - see #139
