### ISSUE TITLE
Contao 4.4+: Add checks for write access to /tmp,  php_mbstring and php_zip

### ISSUE THREAD

**Issue by Arnothar** [contao/check#145]
Your Contao Check (Version 12) is missing 3 additional checks for Contao 4.4+:

1. Write Access to /tmp (or what is configured as temporary directory)
2. Module php_mbstring
3. Module php_zip

Your Contao Check returned "All OK" for Contao 4.4+, but when I was trying to install Contao to Document Root, I hardly had to search for issues. 

Contao Manager is redirecting Error Messages into it's own file which is planned to be displayed while setup. But that isn't working properly.

So, adding those additional checks would be nice.

**Comment by fritzmg** [comment]
See https://community.contao.org/de/showthread.php?71009-Gel%C3%B6st-Contao-4-mit-Contao-Manager-installiert-aber-Installtool-nicht-gefunden&p=475119&viewfull=1#post475119

ad 1) this is already implemented
ad 2) this is not necessary for Contao 4
ad 3) this is not necessary for Contao 4
