### ISSUE TITLE
"Contao installieren" Button löschen oder anders verlinken

### ISSUE THREAD

**Issue by k-webdesign** [contao/check#150]
**Description**  
Huhu,

wäre es möglich, da die 3.5 für Neuinstallationen eh tot sein sollte, den Contao Check entweder um den Button "Contao installieren" zu erleichtern oder bei diesem Button alternativ einen Link auf https://contao.org/de/download.html zu setzen?
Nachtrag: Dass "Bestehende Installation prüfen" noch Sinn macht, bezweifle ich auch. Vielleicht könntest du es um den Hinweis "nur bis Contao 3.5 nutzbar" erweitern.
**Example**  
Siehe https://docs.contao.org/manual/installation/systemvoraussetzungen/ im Screenshot für den Check

🖤🖤

**Comment by xchs** [comment]
> da die 3.5 für Neuinstallationen eh tot sein sollte, den Contao Check entweder um den Button "Contao installieren" zu erleichtern

Ich nutze das beispielsweise schon noch hin und wieder, inbesondere, wenn es darum geht, eine ältere Contao-Installation in einer Parallelinstallation schnell auf Contao 3.5 zu aktualisieren und von dieser schließlich auf Contao 4 upzudaten.

**Comment by k-webdesign** [comment]
Als Kompromiss könnten dann vielleicht 2 Buttons da stehen: einer für 3.5 und einer für Version 4 (mit dem Link auf die Website) 🙂Hauptsache Contao 4 wird irgendwie mit integriert.

Wobei wir uns, gerade wenn es offiziell von Contao bereitgestellt wird, fragen sollten wie lange wir ein totes Pferd weiter mitschleppen wollen.

**Comment by k-webdesign** [comment]
Hintergrund ist, dass mir ein Hoster eine 3.5 installiert hat, obwohl ich ihm nur den Link zu den Systemvoraussetzungen (siehe oben) geschickt habe, um seinen Root Server entsprechend vorzubereiten. Dass er das gar nicht hätte installieren müssen, ist das eine, ich find's nur unglücklich, dass es diese Option noch gibt, wenn Contao 4 schon bald in die 2. LTS-Runde geht, und eben die einzige angebotene Version die 3.5 ist.

**Comment by fritzmg** [comment]
Ich denke es wird generell Zeit den Contao Check in Rente zu schicken, da der Contao Manager die Überprüfung der System Voraussetzungen ohnehin übernimmt ;). Aber ein letztes Update mit entsprechenden Hinweisen macht auf jeden Fall Sinn.

**Comment by fritzmg** [comment]
> Nachtrag: Dass "Bestehende Installation prüfen" noch Sinn macht, bezweifle ich auch. Vielleicht könntest du es um den Hinweis "nur bis Contao 3.5 nutzbar" erweitern.

» https://github.com/contao/check/pull/151

**Comment by fritzmg** [comment]
See https://github.com/contao/check/pull/154
