### ISSUE TITLE
Mark the LTS version

### ISSUE THREAD

**Issue by xchs** [contao/check#26]
It might be useful if we could show/mark in the "Target version" select menu the respective LTS version, too.

![target_version](https://cloud.githubusercontent.com/assets/1218766/6466521/7039a9d2-c1c8-11e4-92ca-7c2193896fe1.png)

**Comment by leofeyer** [comment]
1. Could you please re-upload the broken image?

2. What do you think about only offering the current stable and the LTS version for installation? I feel like we should not allow people to install outdated or insecure versions.

**Comment by xchs** [comment]
> Could you please re-upload the broken image?

Done.

> What do you think about only offering the current stable and the LTS version for installation?

It's okay and definitely makes sense.

**Comment by leofeyer** [comment]
Changed in dcc8a059aad2fffafdbffa475e9de6c330db0091.
