### ISSUE TITLE
Falsche Bewertung der Berechtigungen

### ISSUE THREAD

**Issue by computersalat** [contao/check#54]
'Owner' des html Verzeichnisse: 'ftp-user'
'Gruppe' des html Verzeichnisses: web

Verzeichnisrechte: 2775
Dateirechte: 0664

umask: 002

webserver-user und 'ftp-user' sind Mitglied der Gruppe web, somit haben beide das Recht Dateien/Verzeichnisse anzulegen.
Mit dieser Konfiguration braucht man keinen 'Safe Mode Hack' aber das 'check' programm ist der Meinung man braucht ihn, was schlicht falsch ist.

**Comment by tsarma** [comment]
The check tool assumes file owner is same as the apache user. Thus if you upload "contao check" folder  to the server through ftp, the check folder is owned by that ftpUser, which is most probably different than apache user. So you'll get the error "The PHP process is not allowed to create files."  

Its may be solved by:
1. chown -R apacheUser:apacheGrp ./path_to_checkfolder
OR
2. make both ftpUser and apacheUser in same group. And give permission of 775 to /var/www
chmod -R 775 /var/www
echo "umask 002" >> /etc/sysconfig/httpd
