### ISSUE TITLE
Feature: Add subfolder as Get Param

### ISSUE THREAD

**Issue by Zeromax** [contao/check#64]
It would be cool to have the possibility to change the path to a subfolder where contao is installed via `GET` Param.

So I can have one check installation and check all contao subfolders easily.

I think that this is an enhancement only for local installations ;)

**Comment by leofeyer** [comment]
That sounds pretty error-prone to me, which is probably why you suggested to make the feature available for local installations only. Not something the majority of users needs, is it?

**Comment by Zeromax** [comment]
@leofeyer I think you are right. If this is online there will be to much Problems... So I add this by my own in my local Environment. I haven't thought about the Details.
