### ISSUE TITLE
Contao 4-Kompatibilität

### ISSUE THREAD

**Issue by magicsepp** [contao/check#67]
damit der check erreichbar ist hab ich den check nach domain.de/web kopiert..
Dadurch kommt dann logischweise:

```
Installation

Keine Contao-Installation gefunden.

Um eine bestehende Installation zu prüfen, laden Sie bitte den Ordner "check" in Ihr Installationsverzeichnis.
```

Wie ist das für die Zukunft gedacht?

**Comment by xantippe** [comment]
@leofeyer: wäre es möglich eine "Contao-4-Check"-Alpha zu machen - sprich ein abgespeckte Variante was die Hoster-Kompatibilität zu Contao 4 abprüft...

Dazu gibt es m.E. in der Community die meisten Fragen.

**Comment by tschoening** [comment]
Hi, ich habe gerade ein Problem, dass zumindest in die Richtung /web-Problematik zu gehen scheint und man vielleicht gemeinsam korrigieren könnte: Ich möchte Version 3.5.0 einsetzen und habe diese per git geklont und ausgecheckt, auf die gleiche Weise möchte ich contao-check aber ebenfalls nutzen. Wenn ich das aber in ein Unterverzeichnis klone, das Contao-Root ist ja schon ein Repo, entsteht in dem Repo dann immer wieder das versionierte Unterverzeichnis "check" selbst, man kommt also ebenfalls eine Ebene zu tief, so dass die vorhandene Contao-Installation nicht gefunden wird.

Es bringt auch nichts, mit Symlinks zu arbeiten, in dem man auf der Ebene von Contao einen Symlink auf den versionierten "check"-Unterordner legt, weil beispielsweise Validator mit __DIR__ arbeitet, welches von PHP ebenso wie [__FILE__](http://php.net/manual/de/language.constants.predefined.php) nicht den Symlink-Pfad bekommt, sondern den mit bereits [aufgelösten Symlinks](https://bugs.php.net/bug.php?id=46260). Letztendlich bleibt man so also immer eine Ebene zu tief.

Mein Vorschlag wäre daher einfach, mehrere plausible Elternebenen zu unterstützen und nicht mehr immer hart kodiert von "../.." auszugehen. Ich habe Validator bereits so geändert, dass seine Ermittlung von constants.php die vorherige Verzeichnisstruktur und die beim Checkout per git berücksichtigen kann. Theoretisch kann man dann einfach immer noch eine und noch eine ergänzen, was auch immer man sinnvoll findet. Die Verzeichnisebene, in dem die constants.php letztendlich gefunden wurde, wird dann einfach in der Instanz gespeichert und weiter verwendet.

Letztendlich kann contao-check dann einfach in irgendeinem Unterordner liegen und arbeitet sich seinen Weg zum Contao-Root selbst hoch. In der Regel wird das ja nur eine Ebene mehr sein, als früher, man ist aber flexibler und performance- oder sicherheitskritisch ist das ja auch alles nicht.

**Comment by xantippe** [comment]
jetzt mit der 4.02 und der Möglichkeit ohne Composer zu installieren, wäre doch die "alte" Funktionalität einer Installtion per Check wieder möglich - oder?

Vorab wäre es aber dennoch schön, wenn man ein (kleines) Prüfscript hätte, mit welchem ich alle meine Provider auf die Möglichkeit einer 4.x Installtion abprüfen kann...

Gruss & Dank!

**Comment by jenda77** [comment]
:+1:

**Comment by Fruchuxs** [comment]
Ich muss auch gestehen, dass die Installation der Vierer-Versionen benutzerunfreundlich ist. Zudem versuche ich auch seit ca. 2h 4.2. zu installieren. Zuerst hab ich das über Composer versucht, doch leider habe ich vergessen, meine Konsole mit Adminrechten zu starten und es daher zu einem Fehler bzgl. der Erstellung der Symlinks kam. Was mich wiederum auch leicht wundert, weil ich der Meinung bin, dass Symfony selber als Fallback dann die Files einfach kopiert - ggf. wird hier was eigenes verwendet?

Btw. das Problem mit den Symlinks besteht auch, wenn man die Policies in Windows richtig setzt - scheint ein Problem in Windows zu sein. Hierbei handelt es sich allerdings auch nur um ein Testsystem lokal auf meinem Rechner.

Also habe ich direkt die 4.2. geladen. Zunächst einmal ganz naiv localhost/contao/web/install.php versucht. Eine Lizenzvereinbarung erscheint, ich drücke `Akzeptieren` und ... es lädt. Und lädt. Bis zum timeout.  Dann habe ich es "Symfony konform" installiert, d.h. alles in einen eigenen vhost gepackt, mit DocumentRoot auf /web/ und die install.php ausgeführt. Eine Lizenz taucht nun nicht mehr auf, ich muss direkt das PW für das Installtool eingeben. Also scheint da doch im Hintergrund vorher was passiert zu sein - denke ich. Genau überprüft habe ich es nun nicht.

Das Template vom Installtool wird nicht angezeigt. Aber direkt erstmal eine Warnmeldung: PDO BaseTable View not found ... - nach Anlegen der Tabellen verschwand der Fehler. Trotzdem nicht schön. Nun hat die Installation geklappt aber die Assets sind nicht ordnungsgemäß kopiert worden - das würde ich vmtl. auch noch gefixt bekommen. Der/Die Fehler kann/können nun auch bei mir liegen, da ich nun mit denselben Files mehrere Arten der Installation ausprobiert habe ...

Ach, ich habe auch versucht alles auf /web/ rauszukopieren und habe die includes angepasst. Hat auch nicht funktioniert. Wieso habe ich das gemacht? Ganz einfach: Ich habe mehrere Kunden mit unterschiedlichen CMS Wünschen und natürlich ist da auch gerne Contao dabei. Der Webspace wird gegeben und meistens gibt es nur einen htdocs Ordner und keinen private Ordner. Zudem macht auch die intl-Extension (zumindest wenn nicht vorhanden) mit Contao 4.2 Probleme - dazu gibt's aber bereits ein Ticket.

Auch sind alle Dokumentationen - die zumindest ich finden konnte - zur Installation von Contao 4 veraltet und die Dokumentation wächst seit dem ersten 4.0 Release gefühlt nicht. Vor allem die "Building extensions for Contao 4"-Documentation rufe ich seit dem ersten 4.0 Release regelmäßig auf und nichts tut sich.

Ich bin studierter Informatiker und weiß, wie wichtig eine Dokumentation für ein Softwareprojekt und vor allem wie wichtig später die Usability für die Endbenutzer ist - dazu zählt auch die Installation. Und der eine oder andere kleine Fachinformatiker/Systemadministrator wird hier bei der Installation sicherlich relativ fix überfordert sein und das ganze einfach sein lassen. Ich weiß, dass contao ein OpenSource-Projekt ist und auf mitarbeit angewiesen ist. Daher soll dies hier auch keine Kritik darstellen sondern eher als Anregung dienen, den Fokus für die nächste Version auf eine bessere/benutzerfreundliche Installationsroutine zu legen (vor allem auch für shared Hosts).

Ich werde nun erstmal 3.5. weiterverwenden.

**Comment by leofeyer** [comment]
Ich habe gerade diese Woche https://hostingwerk.de auf Contao 4.2 umgestellt und hatte keines der beschriebenen Probleme.

Natürlich kann man Contao 4 momentan nur über Composer installieren und sicherlich musste ich auch meinen von Contao 3 gewohnten Workflow überdenken. Aber ich kann nur bestätigen, dass Contao 4 sowohl das Programmieren als auch das Deployment für mich deutlich verbessert hat.

Wir arbeiten ja außerdem an einem Contao-Manager, der vieles von dem, was jetzt noch "benutzerunfreundlich" ist, für den Anwender automatisch konfiguriert.

Aber anstatt alles Ungewohnte direkt als benutzerunfreundlich abzutun, sollte man vielleicht auch Neuem mal eine Chance geben und z.B. wie ich hinterfragen, ob die Software oder doch der eigene Workflow angepasst werden muss. In meinem Fall war es ganz klar letzteres. 😄

**Comment by jenda77** [comment]
Ihr Lieben, 

warum kann man nicht einfach Fehler anerkennen und zugeben? Es ist doch offensichtlich, dass viele Nutzer Probleme mit der Installation der 4. Version haben. Nicht jeder ist ein Tiefentwickler. Ich denke, es wäre besser die Kritik anzunehmen und so schnell wie möglich eine benutzerfreundliche Installation von Contao und dessen Erweiterungen anzubieten. ;-)

Während man sich hier immer wieder über die Kritik beschwert und man einigen Nutzern nicht glaubt, dass es wirklich zu kompliziert ist, laufen Contao womöglich Kunden weg und nutzen diese lieber immer mehr Konkurrenz. Darum geht es bestimmt nicht, oder? 

Ich gehe immer weiter davon aus, dass man Contao so weit wie möglich international aufstellen möchte, oder? Aber das kann nur gelingen, und davon bin ich fest überzeugt, wenn Contao immer mehr benutzerfreundlicher wird und auf die Kundenstimmen eingeht - und zu ihnen gehören natürlich auch alle Entwickler, Webprogrammierer, Webdesigner, die sich hier melden und deren Interesse ist, dass ihre Arbeit leichter, nicht schwerer wird und dessen Kunden zufrieden sind. 

Wenn man aber schon lediglich bei der Kerninstallation, d.h. gleich am Anfang scheitert, spricht das eher gegen die 4. Version. Dann wird es leider schnell zweitrangig, mit vielen tollen neuen nützlichen Funktionen die 4. Version kommt, die eigentlich sehr attraktiv erscheinen soll. 

Ich denke, dass es im Interesse aller ist, alle neusten Versionen von Contao an so viele Nutzer wie möglich zu bringen. Daher steht für mich mehr im Raum die Frage: wie können wir das erreichen? Meiner Meinung nach sollte man sich vor allem mit dieser Frage befassen und bald eine Lösung finden und anbieten. 

Wenn ihr Hilfe braucht, sagt bitte Bescheid. 

P.S.: Und falls tatsächlich die 4. Version mehr Vorteile für Webprogrammierer etc. bringt, würde ich toll finden, wann man das verständlich visuell darstellt - am besten direkt auf der Contao-Webseite, damit das jeder schnell finden kann.

**Comment by BugBuster1701** [comment]
Wenn es Probleme bei der Installation gibt, melde dich doch im Forum, damit wir sehen können woran es liegt. Es gibt viele bei denen es funktioniert.
Das Contao 4 höhere Anforderungen an Mensch und Maschine hat, wurde ja frühzeitig bekannt gegeben.
Was daran, bis auf die Möglichkeit, kompliziert ist, ein Kommando im Terminal auszuführen und zu guter Letzt noch die install.php aufzurufen erschließt sich mir nicht.

Die Installation über Composer ist übrigens keine Erfindung von Contao. Das nutzen so einige PHP Projekte.

Und zum Thema Vorteile: Die liegen meiner Meinung nach in erster Linie bei den Entwicklern von Erweiterungen durch den Symfony Kern und die Ausrichtung auf Composer. Das war auch das Ziel der 4.0. In den weiteren Versionen kommen nun auch neue Features dazu die auch für Webdesigner, Redakteure, etc. interessant werden.

Außerdem erhofft man sich durch die Umstellung auf Symfony weitere Programmierer die Symfony beherrschen für Contao zu begeistern für die Stärkung des Contao Core Teams.

**Comment by jenda77** [comment]
Mit den Zielen hört sich das gut an. Meine Frage: Wurden diese Ziele schon erreicht oder kann man absehen, dass diese wirklich erreichen werden können?

**Comment by BugBuster1701** [comment]
Was die Vorteile betrifft für Entwickler würde ich sagen ja. Ich selber bin auch schon auf Composer umgestiegen bei  meinen Erweiterungen, unterstütze aber zum Teil noch das alte ER2.
Wenn der Contao-Manager kommt, dann passt das auch besser für die Nicht-Entwickler.
Ich persönlich hoffe der kommt spätestens mit der 4.3, damit genug Zeit ist diesen zu testen und ggf. zu verbessern bis die 4.4 als LTS kommt.

**Comment by Fruchuxs** [comment]
@leofeyer Ich empfinde den Umstieg auf Symfony und Composer auch als den richtigen Schritt in die Zukunft. Das Framework ist stabil, performant, gut getestet und weitestgehend sicher im Sinne der Security. Und die Verwendung eines Packet managers ist in der Softwareentwicklung üblich; gut, dass das auch in PHP Einzug gehalten hat. Die von mir erwähnten Probleme kenne ich aber nur zu gut von anderen Symfony Projekten (tlw. sogar von meinen eigenen ...). Wie gesagt, vmtl. hätte ich die Probleme auch lösen können, aber nach 2h rumdoktorn bei 30° war es etwas arg frustig und wenn ich dann an einen Webdesigner denke, der sich eine Webseite mit Contao in Eigenarbeit aufbauen möchte - bei der Menge der unterschiedlich konfigurierten Webspaces - wird dieser vermutlich relativ schnell auf ein anderes CMS ausweichen. Und das empfände ich als schade, da ich das Konzept von Contao im Sinne des Content-Managements wirklich sehr gut und durchdacht finde.

Im Grunde wollte ich auch einfach nur darauf Hinweisen, dass eine entsprechende Installationsanleitung fehlt. Habe gesehen, dass auch im Contao Forum darauf einige gestoßen sind.

@BugBuster1701 
```Was daran, bis auf die Möglichkeit, kompliziert ist, ein Kommando im Terminal auszuführen und zu guter Letzt noch die install.php aufzurufen erschließt sich mir nicht.```

Hat sich mir auch nicht erschlossen, als ich für Contao meine Entwicklungsumgebung umstellen musste und die install.php aus dem Web-Verzeichnis heraus (nicht DocumentRoot) ewig geladen hat und erst dann reagiert hat, als ich das Web-Verzeichnis als DocumentRoot deklariert habe. Das kann aber auch an meiner Umgebung liegen, dass möchte ich gar nicht abstreiten. Allerdings hatte ich noch nie solche Probleme (bzw. nur ähnliche mit der Symfony-Standard-Edition).

Zudem muss ich den Konsolen-Befehl auch lokal ausführen um die Installation lokal zu machen um sie dann auf einen Kundenspace zu transferieren. Mit einem "Webinstall" hat das nichts mehr zu tun.


Aber das alles hat sich im Grunde mit der Info zum "Contao-Manager" auch schon erledigt. 


Grüße,
Fruchuxs

**Comment by zonky2** [comment]
ist "Contao-Manager" === "Tenside" ?

**Comment by BugBuster1701** [comment]
@zonky2 Denke ja.
Nochmal zu Installation, es sollte doch auch gehen die ZIP zu laden von contao.org und nach entpacken einfach die install.php aufzurufen, oder geht das nicht mehr? Quasi wie zu Contao 3 Zeiten.

**Comment by zonky2** [comment]
@BB ggf. schon - aber dann hast Du ein "nacktes" Contao...wie willst Du dann die Erweiterungen einspielen (ohne Composer)

**Comment by BugBuster1701** [comment]
Hier ging es erst mal um die Installation von Contao 4 selbst. Alles andere folgt dann.
Da dort die composer.json und .lock dabei ist, kann man danach versuchen mit composer weiter zu machen und die Erweiterungen zu installieren. Davon gibts aber eh noch wenige.

@leofeyer : Auf contao.org wird noch die 4.1.3 angeboten, nicht die 4.2.0.

**Comment by leofeyer** [comment]
Diese Diskussion ist im [Forum](https://community.contao.org/de/) sicherlich besser aufgehoben.

**Comment by leofeyer** [comment]
@BugBuster1701 Vielen Dank für den Hinweis, ich habe den Downloader angepasst.

**Comment by fritzmg** [comment]
I'll may be integrate a check whether a Contao 4 installation was detected, including a notice that the Contao Check cannot check the integrity of Contao 4 installations.

**Comment by fritzmg** [comment]
See https://github.com/contao/check/pull/151
