### ISSUE TITLE
Composer wird in "Weitere Informationen" als verwendbar angezeigt, obwohl das nicht stimmt

### ISSUE THREAD

**Issue by tristanlins** [contao/check#75]
In der Übersicht steht korrekterweise:

> Sie können die Composer-Paketverwaltung nicht verwenden. Weitere Informationen … 

Unter "Weitere Informationen" erscheint dann allerdings:

> Sie können die Composer-Paketverwaltung auf diesem Server verwenden.  

Siehe https://community.contao.org/de/showthread.php?54973-Composer&p=354637&viewfull=1#post354637

**Comment by leofeyer** [comment]
Behoben in 5cfb88e09c9a7da490ee6b10961f5650796332fc.
