### ISSUE TITLE
Security issues in Contao Check

### ISSUE THREAD

**Issue by abuchoux** [contao/check#78]
Hi,

I have found security issues in Contao Check.
How can it be reported in order to avoid revealing the issues before it's fixed?

Regards,
Arnaud

**Comment by leofeyer** [comment]
Please write an e-mail to security [at] contao.org.

**Comment by leofeyer** [comment]
Meanwhile fixed in acfa951e2017f1dc736d2dd66e6c732e98b2c247. Thanks again for your help @abuchoux.
