### ISSUE TITLE
Checkbox to auto-update corrupt files

### ISSUE THREAD

**Issue by Ruudt** [contao/check#79]
Can you add a reset option in the check tool? A checkbox in front of each corrupt/missing file to make the tool fix these files. Sometimes fixing each file that became corrupt/missing (during upload) takes a while. But in some cases you do not want to save each mentioned file.

Check tool can update directly from the concerning Git commit.

First asked as a sidenote in #44

**Comment by leofeyer** [comment]
The Live Update provides exactly this functionality.
