### ISSUE TITLE
/check/?c=validator | You cannot access this file directly!

### ISSUE THREAD

**Issue by ciaobello** [contao/check#80]
Contao Check 10.0

If i try to run "validate an existing installation" (2.11.11) I get the following message:
**You cannot access this file directly!**
URL shows:  **example.com/check/?c=validator**

I use a development environment on a VirtualBox.

(In my case a downgrade to Contao Check 9.13 solved the problem)

**Comment by leofeyer** [comment]
Fixed in d1243462225ce0afdfbfd5184df77d75e1bc7a6f.
