### ISSUE TITLE
file permission check

### ISSUE THREAD

**Issue by kaeptn2lvl** [contao/check#82]
on a 1und1 webhosting php is able to write and create files and directories. I ve checked it myself with a very simple script:
	$testdir=@mkdir('test');
	echo var_dump($testdir);
	if($testdir){
		$ourFileName = "test/testFile.txt";
		$ourFileHandle = fopen($ourFileName, 'w') or die("can't open file");
		fclose($ourFileHandle);
	}
Testfiles and folder were visible after running the script.
but contao checks 9.7,10.0, and newest one  are telling me that the php process does not have file creation rights... which is not true, also it tells the wrong permissions "705", but it is actually "777"

**Comment by leofeyer** [comment]
What exactly does the Contao check say?

**Comment by kaeptn2lvl** [comment]
![contao_check](https://cloud.githubusercontent.com/assets/6260610/7199537/e279acae-e4f5-11e4-825c-63cef22c9f06.JPG)
![contao_check2](https://cloud.githubusercontent.com/assets/6260610/7199540/e53086a2-e4f5-11e4-9777-7d3c2caadbca.JPG)

**Comment by kaeptn2lvl** [comment]
btw. 9.7, 10.0 and current version say the same

**Comment by leofeyer** [comment]
We just have to add 705 and 604 to the list of known chmod values.

**Comment by kaeptn2lvl** [comment]
perfect and thx.

**Comment by kaeptn2lvl** [comment]
also could it be that "core/library/Contao/File.php" does use the similar method for checking? Because from there I get sometimes 
"PHP Fatal error: Uncaught exception 'Exception' with message 'Cannot create file' "

But that is another issue I did not dive into yet, and I am not sure if it is my installation, or some extension... so just wondering...

**Comment by leofeyer** [comment]
Fixed in cfb142f7866ebcb79d549628b9d0c84227e5819d.
