### ISSUE TITLE
wrong information installable Contao versions

### ISSUE THREAD

**Issue by frontendschlampe** [contao/check#83]
When I access the Contao check in my browser there will be the informations which version of Contao I can install. The information for Contao 3.x isn't correct because Contao 3.2 don't need PHP 5.4 so you can't write

> You cannot install Contao 3.x (requires PHP 5.4.0+)

Maybe you can differentiate a little bit.

**Comment by fritzmg** [comment]
:+1:
I also think it should differentiate between PHP 5.3.2 (Contao 3.0.x - 3.3.x), PHP 5.3.7 (Contao 3.4.x) and PHP 5.4.0 (Contao 3.5.x).

**Comment by fritzmg** [comment]
Closing as this issue is outdated.
