### ISSUE TITLE
zusätzlich auf GD Library prüfen

### ISSUE THREAD

**Issue by Marion04** [contao/check#85]
Wenn auf dem Server die GD Library nicht läuft, werden in Contao die Thumbnails nicht korrekt dargestellt. Ich habe bei einer Installation 2 Tage lang nach dem Fehler gesucht. 
Meine Anregung: Könnte man den Test, ob die GD Library enabled ist, in den Contao Check aufnehmen? Dann müsste nie wieder jemand so lange suchen... ;-)

**Comment by thomaspahl** [comment]
+1
Contao 3.4.5 mit PHP ohne GD: alle Bilder blieben full size (BE/FE), keine Fehlermeldungen in system/log, keine in PHP, keine im Apache log. Mangels Fehlermeldung sucht man länger, bis man auf die Idee kommt, die GD extension zu prüfen.
Check sollte auf die must-have extensions prüfen (auf die optionalen für erweiterte Funktionen wird ja schon geprüft).

**Comment by fritzmg** [comment]
:+1:

**Comment by fritzmg** [comment]
This is implemented in #108 now.
