### ISSUE TITLE
Error beim Check-Aufruf

### ISSUE THREAD

**Issue by alex1971** [contao/check#86]
Folgender Error erscheint beim Aufruf des Checks:

"Fatal error: Cannot redeclare posix_getpwuid() in /usr/home/XXXX.com/web/check/controller/bootstrap.php on line 173"

PHP Version 5.4.41-0+deb7u1

**Comment by BugBuster1701** [comment]
Hast du eine neue Version vom Check irgendwann mal über eine alte drüber installiert?
Falls ja, lösche mal das check Verzeichnis komplett und installiere den Check neu.

**Comment by alex1971** [comment]
Danke für die schnelle Antwort, hab's probiert, das Verzeichnis ganz gelöscht, nochmals raufgeladen und ausgeführt. Gleicher Error erscheint...

**Comment by alex1971** [comment]
Server Update auf PHP Version 5.4.42 gemacht und nun klappt alles!
