### ISSUE TITLE
Aufruf der .../contao/install.php von spanischen FF-Browser zeigt Error an

### ISSUE THREAD

**Issue by alex1971** [contao/check#87]
Hallo,
von der spanischen Community wurde mir über ein Error berichtet, der offenbar nur in Spanien auftaucht. Ich habe mir daraufhin den Firefox in spanisch installiert und konnte die Fehlermeldung auch sehen, folgender Error erscheint beim Aufruf vom install-tool (egal ob die Seite auf einem spanischen oder deutschen Server liegt) von einem spanischen Browser aus (getestet mit FF, IE und Chrome):
___
Warning: sprintf() [function.sprintf.php]: Too few arguments in system/modules/core/controllers/BackendInstall.php on line 861
#0 [internal function]: __error(2, 'sprintf() [\xC2\xA1Ate...', '
___
Das Layout wird auch nicht optimal dargestellt (siehe Screenshot).
Beim Aufruf mit einem deutschsprachigen Browser klappt wiederum alles problemlos.

![screenshot](https://cloud.githubusercontent.com/assets/6985539/8593189/c0ce86f2-2635-11e5-99e5-aa9286629d7e.jpg)

**Comment by xchs** [comment]
Dieses Ticket gehört nicht hier her, sondern in das "contao/core" Repository.

Der Fehler dürfte vermutlich durch einen Syntaxfehler in der spanischen Übersetzung herrühren. Ich habe schon etliche Male versucht, die Mitglieder der spanischen Übersetzungsgruppe auf Transifex auf solcherart Tipp- oder Syntaxfehler hinzuweisen. Bislang leider immer vergeblich.

**Comment by alex1971** [comment]
Besten Dank!
Bin neu im Github, sorry hab's zu spät bemerkt und wollte es ins contao/core schieben, hab aber nicht gefunden wie das geht. Kann man das überhaupt?

Betreffend dem Fehler, welcher im Transifex korrigiert werden kann, bist Du bei mir genau richtig, ich bin seit ein paar Monaten neu verantwortlich für die spanische Übersetzung. Kann ich das indem Fall selber erledigen?

**Comment by xchs** [comment]
> ich bin seit ein paar Monaten neu verantwortlich für die spanische Übersetzung. Kann ich das indem Fall selber erledigen?

Ah, super. Natürlich kannst Du das dort selbst fixen. Ich schau gleich mal, ob ich den fehlerhaften String dort finde und melde mich dann ggf. über Transifex bei Dir.

**Comment by alex1971** [comment]
ok bestens! Danke!
So wie es aussieht liegt der Fehler auch beim Login-Fenster für das Backend. Ich kann es hier mit dem spanischen FF sehr gut austesten...

**Comment by xchs** [comment]
Der Fehler liegt ziemlich sicher hier: https://www.transifex.com/projects/p/contao/viewstrings/#es/v3_5-core-default/42426394

In der spanischen Übersetzung gibt es ganz am Anfang und auch am Ende jeweils einen Stringplatzhalter `%s`, der da nicht hingehört. Vielleicht kannst Du das für v3.2 und v3.5 entsprechrend richtigstellen.

**Comment by alex1971** [comment]
Danke für die Hilfe! Hab's im Transifex korrigiert.

**Comment by xchs** [comment]
:+1:
