### ISSUE TITLE
Installtion über Check-Tool 10.16: Ordner /system in "Unterordner" /contao-3.5.12

### ISSUE THREAD

**Issue by zonky2** [contao/check#96]
bei der Installation über das Check-Tool wurde der System-Ordner in einem Unterordner /contao-3.5.12 installiert

Mampp auf Windows (Contao2go)

**Comment by leofeyer** [comment]
Das ist soweit korrekt. Der Fehler ist, dass der System-Ordner dort verblieben ist und nicht in das übergeordnete Verzeichnis verschoben wurde.

Ich kann das Problem jedoch hier nicht reproduzieren.

**Comment by zonky2** [comment]
soben nochmal getestet - Problem besteht (bei mir) weiterhin

![shot205](https://cloud.githubusercontent.com/assets/1045318/15183847/23092c06-1793-11e6-9003-e4c542f56365.jpg)

**Comment by zonky2** [comment]
ich habe mir vom Install ein echo bei

```
				// Remove the wrapper folder (see #23)
				foreach (scandir(__DIR__ . "/../../$prefix-$version") as $file) {
					echo $file."<br>\n>";
					if ($file != '.' && $file != '..') {
						rename(__DIR__ . "/../../$prefix-$version/$file", __DIR__ . "/../../$file");
					}
				}
```

ausgeben lassen

```
.
>..
>.github
>.gitignore
>.htaccess.default
>assets
>build.xml
>composer.json
>composer.lock
>contao
>files
>index.php
>README.md
>robots.txt
>share
>system
>
Warning: rename(C:\Contao2Go\htdocs\vhosts\contao-3.5.x-test\check\controller/../../contao-3.5.12/system,C:\Contao2Go\htdocs\vhosts\contao-3.5.x-test\check\controller/../../system): Zugriff verweigert (code: 5) in C:\Contao2Go\htdocs\vhosts\contao-3.5.x-test\check\controller\installer.php on line 353
templates
>vendor
>
Warning: rmdir(C:\Contao2Go\htdocs\vhosts\contao-3.5.x-test\check\controller/../../contao-3.5.12): Directory not empty in C:\Contao2Go\htdocs\vhosts\contao-3.5.x-test\check\controller\installer.php on line 357
```

lt. http://php.net/manual/en/function.rename.php#56576 scheint das ```rename``` unter Win ein Problem zu haben...

**Comment by leofeyer** [comment]
Tritt das Problem außerhalb von Contao2Go auch auf?

**Comment by zonky2** [comment]
die primäre Frage ist m.E. nicht Contao2go sondern "Windows" bzw. andere "WAMP-Pakete"

**Comment by leofeyer** [comment]
Und?
