### ISSUE TITLE
Increase Contao 4 PHP version requirement

### ISSUE THREAD

**Issue by fritzmg** [contao/check#97]
The check still only has PHP `5.4.0` defined as the minimum requirement for Contao 4 (» https://github.com/contao/check/blob/10.18/check/controller/index.php#L26). However, since Contao `4.1.0` the PHP minimum requirement has increased to PHP `5.5.0` (» https://github.com/contao/standard-edition/issues/37).

**Comment by leofeyer** [comment]
Fixed in e746f432f76bda905b223c2c84309df5a950d6e5.
