### ISSUE TITLE
File write check makes false assumptions

### ISSUE THREAD

**Issue by lphooge** [contao/check#98]
I get the error message "The PHP process is not allowed to create files." and "The test folder does not have the correct owner or chmod settings"

This is false, the server is set up with ACLs, and the owner is not relevant.

The check script should not try to calculate permissions itself, that is the job of the operating system. There are too many possible configurations to have any hope of duplicating them all correctly in a small installer-script!

I would suggest just doing the file operations (create/read/write/delete) that you want to check and determine if they succeeded.

**Comment by mgla** [comment]
This is an issue for us:

Example:

* Contao installed in /var/www/html
* Webserver running as user httpd
* checks/controller/file-permissions.php` permissions:
  * permissions `0660`
  * user:group: `maintenance:httpd`

While the process can absolutely (and does) create the test directory and test files, it tests if the user `maintenance` can write the file created be the process user (`httpd`) and assumes falsely that the file can not be modified. Maybe use [`is_writable()`](http://php.net/manual/de/function.is-writable.php) instead?

**Comment by fritzmg** [comment]
Is this related to https://github.com/contao/check/pull/62 ?

**Comment by lphooge** [comment]
Kind of, that pull requests does exactly what I criticised, and more of it ;)
There really is no point in duplicating unix file mode / owner logic, since there are too many configurations where those are misleading or irrevant anyways.

**Comment by fritzmg** [comment]
Agreed. However, since we are phasing out the Contao Check, I think I'll just leave the current implementation. I don't see much point in putting effort into changing it.
